import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import ts from 'typescript'
const source=readFileSync(new URL('../src/lib/submissions.ts',import.meta.url),'utf8')
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText
const module={exports:{}}
new Function('module','exports',js)(module,module.exports)
const {newRecipeInput,recipeSubmissionPayload,restoreRecipeInput,validateRecipeInput}=module.exports
function complete(){const i=newRecipeInput();i.title='  Soup  ';i.difficulty='Easy';i.total_time_minutes='20';i.ingredients[0].name='Water';i.steps[0].instruction='Boil.';return i}
test('incomplete recipes save as drafts but cannot publish',()=>{const i=newRecipeInput();assert.deepEqual(validateRecipeInput(i,false),[]);assert.equal(validateRecipeInput(i,true).length,5)})
test('minimum complete recipe publishes without photos, quantities or nutrition',()=>{assert.deepEqual(validateRecipeInput(complete(),true),[]);const p=recipeSubmissionPayload(complete());assert.equal(p.title,'Soup');assert.equal(p.servings,null);assert.equal(p.ingredients[0].amount,null);assert.equal(p.steps[0].step_time_minutes,null);assert.equal(p.nutrition,null);assert.equal(p.ingredients[0].key,undefined)})
test('enabled nutrition requires all four values and permits zero',()=>{const i=complete();i.nutrition={calories:'0',protein_g:'',carbs_g:'',fat_g:'',is_estimated:true};assert.equal(validateRecipeInput(i,true).length,3);i.nutrition.protein_g=i.nutrition.carbs_g=i.nutrition.fat_g='0';assert.deepEqual(validateRecipeInput(i,true),[]);assert.equal(recipeSubmissionPayload(i).nutrition.fat_g,0)})
test('invalid quantities and fractional cooking times cannot save',()=>{const i=complete();i.total_time_minutes='1.5';i.ingredients[0].amount='-1';i.servings='0';assert.equal(validateRecipeInput(i,false).length,3)})
test('server drafts restore numeric values to editable strings',()=>{const i=complete();i.ingredients[0].amount='0.5';const p=recipeSubmissionPayload(i);const restored=restoreRecipeInput(p);assert.equal(restored.total_time_minutes,'20');assert.equal(restored.servings,'');assert.equal(restored.ingredients[0].amount,'0.5');assert.deepEqual(validateRecipeInput(restored,true),[])})
const screen=readFileSync(new URL('../src/RecipeUploadScreen.tsx',import.meta.url),'utf8')
function saveAction(context){const ast=ts.createSourceFile('upload.tsx',screen,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let fn;function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text==='save')fn=n.getText(ast);ts.forEachChild(n,visit)}visit(ast);const js=ts.transpileModule(fn,{compilerOptions:{target:ts.ScriptTarget.ES2020}}).outputText;return new Function(...Object.keys(context),`${js};return save`)(...Object.values(context))}
function saveSetup(response){const state={},calls=[];const context={guard:{current:false},editable:true,input:complete(),initial:{id:'draft'},version:'version',cacheKey:'cache',validateRecipeInput,recipeSubmissionPayload,errorPanel:{current:null},requestAnimationFrame(fn){fn()},localStorage:{removeItem(){}},console:{error(){}},supabase:{async rpc(name,args){calls.push({name,args});return response}},onSaved(id){state.saved=id},...Object.fromEntries(['Errors','Message','Busy','Version'].map(n=>[`set${n}`,v=>{state[n]=v}]))};return {state,calls,context}}
test('publish confirms a persisted recipe id and sends optimistic draft version',async()=>{const {state,calls,context}=saveSetup({data:{id:'draft',status:'published',recipe_id:'recipe',updated_at:'new'},error:null});await saveAction(context)(true);assert.equal(state.saved,'draft');assert.equal(calls[0].args.p_submit,true);assert.equal(calls[0].args.p_expected_updated_at,'version');assert.equal(state.Version,'new')})
test('failed saves or missing published ids keep the form without success',async()=>{for(const response of [{data:null,error:{code:'40001'}},{data:{id:'draft',status:'published'},error:null}]){const {state,context}=saveSetup(response);await saveAction(context)(true);assert.equal(state.saved,undefined);assert.equal(state.Errors.length,1);assert.equal(context.guard.current,false)}})
test('busy or invalid publish attempts do not send a write',async()=>{for(const busy of [true,false]){const {calls,context}=saveSetup({});context.guard.current=busy;if(!busy)context.input=newRecipeInput();await saveAction(context)(true);assert.equal(calls.length,0)}})
